apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgA4eDy3LFNK3dqgyg7WH0NGdUiLXRgxIrGpFIwhfJhA6hxm8X+Ty6af8tiIDaj6ic3y2piAQBYPxEIAnbqVYcX6j+tGAn6qchVDt71a9tx6yTeBIvYo1d1E3SppdrrLJ58sPPHE9WHrVgtvyTdSehFR8kKY+ZgHJXkSm9Fc5wnFwqLjczVOoVFcgv5EZjmDLob6lRy/1ohA3zbopwvCvAnPowKVLdmctIHaIj3IB77m5VQbbhTLZD4hl6TzlV/7EXpzzRCWh6TqJJKt9hQyqUf71TmyWgUoCG5BjPZEHSzNvnpzEHta/gxRcaUNk2n4btD7cIW4vQDA3wg6/A8z65l6vXOxzHsTuSXFMDdyrfioA1/07/HiVrGy3Sf+3UwlacRAIT5W+3FLEMADNB70f1YFeO8mXERWKSRm5aoKhRyW9M2FMHq9o20HABXvVhBJa0TdGm2oXwSw/hhxKcGfEY8ukf1rPSixRMRO2Yg+Gcr+5r63o2YjKJQehyORxVP3Wn/N5i4robidlmUEUY+LOM4tv6qcy124libRpCkvrhWB4DFfkmKLVq+JQ6MNZqVULU0O6gvIRPUccJ5+rXqqUEwnmaqfcKG0wUy/dPmdMLB6KuzrvRFMWnRo8Pd98J00reYYgHsem40GmWKGDSMSmuv6szefP0GxARqZ7SleQRndQ2lMt+FrGCJSMgh1JkQJUUXBMAkEbSALOvbnjtU86vVkyCz8hv7tS9W7EbOrIz2cxkLQPom0z7lX/UwdWnlaYw0EfKoKPYfzaAAp9Ple9Lxdil9gQAP9icAFVjYKr5/KsJ9JutrGClC5VaMjiykXXdgNcPnvBwT0IPYSW7PZWORHgR9GmH2yqPZ+plR4yV4fKb/dmM8crSZFGlHsEea5vq40gqTbmCntRsUj847ETk8NcFIpUql3Z8vSUQZ0zbpVfcF3hcGviZDLaV0pb1plKQLScUhhEznV8sao7tMl+8+FJxtQ1mQUDnGh8OAmcN1cVXjKTlsG8wrdJ2XK7stoh9U0VQYMB1Qi0AAZWAg3tGhlRcR3QxoyPZUN3BP5whq9crxAGEpLH4J3qUToViE316zN87sqcmOJQQZ/q4NCdNh6PHxTblLuSdgTfNuiQ1pDQIPkOzOOTFuCXpqnrgTtz5dumHjiEsYWtp+89Te8T4pY3J0SqKVbyJG+X+ksAeZ6jvrxM3XHAAwpc1WcRR04bL4AdVHNlJNxTCtnH7RP2iBXA8kaq8lylMnxGiJcjgV1nysiA9SJbkLCq6USXP2jXscq14ZxP6iTXQ5j1WA08W+/kr3QVSdWi7EJIA0Kk7xCAWDZa2Wg+vb3draoRe+uB4Qp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

