apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgCVALveshI8UuKHwJsET2d7yX6eVHqQ8oaZsun3MA60UtSQtehII1j5okN2ZGcoUqgPU+7o+l7sBT++Hp8ZM5jJf5yRwgrl1PhvOVKGZEDErB7wh2EjPk8YjVEA6qIQPWnF58ylbSsoHKxjH1OFTLwfYiYkuHKv1ABG4iInfbscAxoZCNUO+huJdNoX4zo6ktLCxQOCi6fgMLdF2l/w7zACHAl1j3tcS2/aNwFXTWYDAI/gz+sR8/TxHd9CBtY3dTEZX/ZKWlexNlP+QuRNtauP05p7CQLCywdLWax0GyATHnIadQOOTAjUNWmaUVOdjcG1gagXRH5Zy5kR5scc3XdN9gHVkm3j5Ru24Y0/Z258BlHQpHW/6BkIxtAOu1EkbILF9r0RKT35+xcTuu4XA8fhd26SDJGV/Mz1LQL9azawe2EfXoQBpMRuwt0jcxG5JlnQ9HVZTl/igyNgQeNSjE1Lpa1SHUCb7+QSFqZUjEdMMqE6OE0w33efE6kRf4/rGomHJYNE0oZJqD5ZFb/Qd/Stn5LLjH909zJHPu84KtALUD4PSSjeigS1lZOTMLbDk3xH7z7vbgthkdJK14Ve9WrWqtIyt4ZStmUIQ8iLX6Gb2pAFUp3HJ60dIwIHwjz+NPHnHu2w1ZJbCKWWXRZ0bC4aVjUm6V/eQEnf2x8JDET6WDjVUiCdIea3LQOdrUNu+l4/P89yG4yCPFWCxsm8yJy56WBEuht3Vb+7xrMv9/0WuZ8QXIFyB30va5ViaKbQz7/brBtG3LgcXwYG06puT7ACdjBD8HWglIL1+nlcQyneNJ/0mcMymXR00REe0GNDyebTwYgJqZ/4kLpLFUVpuIIASKGWndDGFfcQG1eg5wr6vN8D7CgEAlxxKBgUBhku/DWK7Np2qVKj+9of2TuKePHAA1VZAD76RWr9mlE+bL/ox6o/U9Cx8K55NTYHGTinGXvkxcG+Q594keZy0NVrr1Z4/pH4u+Fy6Lsv8nQeoo0rqkhIVFFkBZX+VVKI1O/rv9nDz6W8vl1UCcl99YAV9UlT91UB/00C0IZoLXTe3DkTIODcbLHiYJpPWp+a+wIphcNFjSOKJWPXb0SzGmKVZn2Ry/gQpodG3fmWnk/LW3zpi01tGR6obzTPQjzqBLszvrhBzjcQScQWc9PauGyVbjEoBMLXDzK3jr+P/fRdW3q0zb5XQ58k3m2TXlJiKNUpFv9gge073IYSh1I/P1KZoB4uIzZKxxeY3eMFh+2y4E/4rWRb5fM69EdMLKVZlDLJnlh14uAlMJcS+uMHi3JtCqnpWZBd7cb5SNfvuJhBlyTrbsucFDdClNp+DGvxSJo2RcGD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

