apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgCDTGF0fPz+7hP3ScJ3Hy9HIus7z/wSDpsIRd/p5bRNVscqTh7e4Mrg67N8NbQgmovLCcuXS+j4jgePaxeovxF/F9zr89E+3Fh2xPQnMXTXsLEPdwH+GsgiQ2rWi9FQWl9EtSISlSW8RpT9m7YQdm/xtg7TqoNnMUT/y6gL/BxwNq/wFuLHPWKPxVwCTf0cVHku54M3zvvDOUQ8YDAGqscD+cF0tbcsPtSh+RAIHRhGVBN3CdJOODnJWm4XaL5L+QRtk4zuhb0jAY2dI24CE32uZ3SGN7oQYu2ih4NwTLTwdPo4lhUdcj7ySdOvXmgQguneSUvCavGYFbOp7IQyWqUUk6bARA33gN6PsylX3WHekoqFEdlM1N1+bV2MDdcjHdGhe6VQShEkTiAq4xUQqT+AlORmSFqsosovtXL4kM8JP1QQg1EyhmmaUniV3VTu7vclm9v2UURGEESTj3hs3al9OFvuB/HoRWI8COeMBqdxqqHZnrpir+2sFHIzRfB0pUIdeKvNIPXZvnCpk2jSQR9PlOl/VDDfhbgPncalQgVsAFRVMDAPbnyh+MT+nuw1ggZiGwRm3IjR3gHzPWsj02/qyBnbsEO6JLAe4Zyeh67O3+Ac1FvBtFZ5LpO0o1A9zJ3YJSdjb+/9IQDOJ74OrMXxTl5nhZ9zcj2X0mIVHHcLRtb+pJqkUdSH5ZrL8I+lotl1ijcfW3JcddD8kEZEC1VODHwSZlaKuz+Qz9mBIAZcr65TjKaXJW78bi4W4Xq+MqOV6ofDIf3vmSMgpoEfY8DLfBpKeaLNxI3BLXGfkPl6oIaOVRNPPGaDznhJboePefW8pkqgat1/tZFN6CJOy9Pkl7B4JztrflpwZQ3KYC6k8eB0JdK8gZmrxpla+Rh6u37JTJ2Xks9y7aWyVONePCraHjL1ja5YEKBJ5BtqRqrx1dSPIMp6igIVdVLHmdErHBI1/7eop65WCuuES574oT7Bgzx1D+OiP71pE3g4LdiEpPjiQEwUHtUzRejvKEw4WHSdOx/V7rdIqKx0RjI1iWNFtT7B1FYMKcF4kP2aIx7jaRaUXQ5BSVevY/4YX4FDbokos/tOza6+r3AijL/ramDfV2XHM6zxb9Xab32qPT3oeaPOq98gVoUTFecZ3Ajozqc4nW5o/J4U4NqWu66RrR2+9wHvlpHcyDN3tucHRGvyd+K3N9QnQhTkOpRMalkJAVSo1IhpYSgTT15c0al57u/Ih8S2bfUtlQBlsZYNXixb+F21Vr3JdYFIUrYzwlC6/1vmi//MTqInQisDVBmO+h3ldysz7Bcz5agPfAx5nX4GJ/ExCSeJXNZzahxSVAIyTTUm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

